// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiu2fFUSQB0V3MDd_EoesgDk1pLTKfXxE',
    appId: '1:845932429937:web:c59f4b73101958f864d1d0',
    messagingSenderId: '845932429937',
    projectId: 'coachsync-e5cb1',
    authDomain: 'coachsync-e5cb1.firebaseapp.com',
    storageBucket: 'coachsync-e5cb1.firebasestorage.app',
    measurementId: 'G-41PNTK7SXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPCdIg4BmM4C0II1LwlpWVISKuTgeQkA',
    appId: '1:845932429937:android:48a390ce3837055464d1d0',
    messagingSenderId: '845932429937',
    projectId: 'coachsync-e5cb1',
    storageBucket: 'coachsync-e5cb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYCn7Hd-hzO9UDTsK_SQhnNW8LDBQK3c',
    appId: '1:845932429937:ios:8a019d3fde676b6964d1d0',
    messagingSenderId: '845932429937',
    projectId: 'coachsync-e5cb1',
    storageBucket: 'coachsync-e5cb1.firebasestorage.app',
    iosBundleId: 'com.example.coachsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYCn7Hd-hzO9UDTsK_SQhnNW8LDBQK3c',
    appId: '1:845932429937:ios:8a019d3fde676b6964d1d0',
    messagingSenderId: '845932429937',
    projectId: 'coachsync-e5cb1',
    storageBucket: 'coachsync-e5cb1.firebasestorage.app',
    iosBundleId: 'com.example.coachsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiu2fFUSQB0V3MDd_EoesgDk1pLTKfXxE',
    appId: '1:845932429937:web:40c8993abddd8cf964d1d0',
    messagingSenderId: '845932429937',
    projectId: 'coachsync-e5cb1',
    authDomain: 'coachsync-e5cb1.firebaseapp.com',
    storageBucket: 'coachsync-e5cb1.firebasestorage.app',
    measurementId: 'G-LH71XBVBH0',
  );
}
